name: main

on: [ push ]

env:
  DUMMY: a

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: './src ./test'
          exclude: './lib ./tools'
          extensions: 'h,cpp'
          clangFormatVersion: 18.1.8
          style: file
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set VERSION_SUFFIX
        shell: powershell
        run: |
          $branch = git rev-parse --abbrev-ref HEAD
          $commit = git rev-parse --short HEAD
          $VERSION_SUFFIX = "-$branch-$commit"
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Display VERSION_SUFFIX
        shell: powershell
        run: echo "VERSION_SUFFIX is $env:VERSION_SUFFIX"

      - name: CMake Setup
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: cmake --preset vcpkg-win64-x86
         
      - name: CMake Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: cmake --build build

      - name: CMake Test
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ctest --test-dir build

      - name: 'Upload x86-sse2 build'
        uses: actions/upload-artifact@v4
        with:
          name: mupen-x86-sse2
          path: build/out
          retention-days: 14